name: Ping Supabase

on:
  schedule:
    - cron: "0 0 * * 0" # Every Sunday at midnight UTC

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
      - name: Call Ping Function
        run: curl -X GET "https://dennisochfanny.vercel.app/api/ping-supabase"
